const translations={"pt-BR":{"site-title":"Minhas Builds","hero-title":"Todas as minhas builds de jogos e projetos","hero-subtitle":"Encontre aqui todas as versões disponíveis para download","builds-title":"Builds Disponíveis","modules-title":"Módulos","modules-description":"Módulos personalizados para expandir e melhorar suas builds","team-title":"Equipe","donation-title":"Apoie o Projeto","donation-description":"Se você gosta do meu trabalho, considere fazer uma doação para ajudar no desenvolvimento contínuo!","support-title":"Grupo de Suporte","support-description":"Junte-se ao nosso grupo de suporte para tirar dúvidas, compartilhar feedback e conversar com outros usuários","footer-text":"Feito com ❤️ por Vinicius Sad | 2026","download":"Baixar Agora","language":"English","total-downloads-text":"downloads totais"},"en":{"site-title":"My Builds","hero-title":"All my game builds and projects","hero-subtitle":"Find all available versions for download here","builds-title":"Available Builds","modules-title":"Modules","modules-description":"Custom modules to expand and improve your builds","team-title":"Team","donation-title":"Support the Project","donation-description":"If you like my work, consider donating to help with continuous development!","support-title":"Support Group","support-description":"Join our support group to ask questions, share feedback, and chat with other users","footer-text":"Made with ❤️ by Vinicius Sad | 2026","download":"Download Now","language":"Português","total-downloads-text":"total downloads"}};
let currentLang='pt-BR';
let config={};
let liveData={totalDownloads:0, items:{}};
function setText(id, txt){const el=document.getElementById(id); if(el) el.textContent=txt;}
function getSavedToken(){return localStorage.getItem(GitHubDownloadAPI.tokenKey||'gh_pat_token');}
async function loadConfig(){ const r=await fetch('config.json',{cache:'no-store'}); config=await r.json(); window.siteConfig=config; await loadData(); initializeSite(); }
async function loadData(){ try{ liveData = await GitHubDownloadAPI.readData(); } catch { liveData = {totalDownloads:0, items:{}}; }
}
function updateLanguage(){ const t=translations[currentLang]; Object.entries(t).forEach(([k,v])=>setText(k,v)); document.documentElement.lang=currentLang; loadBuilds(); loadModules(); loadTeam(); loadDonation(); loadSupport(); updateCountersUI(); }
function updateCountersUI(){ setText('total-downloads-count', Number(liveData.totalDownloads||0).toLocaleString(currentLang==='pt-BR'?'pt-BR':'en-US')); }
function itemCount(type,id){ return Number(liveData.items?.[`${type}_${id}`]?.downloads || 0); }
function initCursorGlow(){const g=document.getElementById('cursorGlow'); if(!g) return; document.addEventListener('mousemove',e=>{g.style.left=e.clientX+'px'; g.style.top=e.clientY+'px';});}
function initHeaderScroll(){const h=document.getElementById('header'); window.addEventListener('scroll',()=>h.classList.toggle('scrolled',window.scrollY>100));}
async function incrementDownload(type,id){ try{ liveData = await GitHubDownloadAPI.updateItem(type,id); updateCountersUI(); const el=document.getElementById(`${type}-${id}-count`); if(el) el.textContent=itemCount(type,id).toLocaleString(currentLang==='pt-BR'?'pt-BR':'en-US'); } catch(e){ console.error(e); alert('Não foi possível atualizar o contador global. Configure o token no navegador.'); } }
function cardBase(title,desc,img,version,date,downloads,btnTxt,extra,downloadUrl,type,id){ return `<img src="${img}" class="build-image" onerror="this.src='https://via.placeholder.com/400x220/12121a/a855f7?text=Image'"><div class="build-content"><h3>${title}</h3><span class="build-version">v${version}</span><p>${desc}</p><p class="build-date"><i class="far fa-calendar"></i> ${date}</p><div class="module-downloads"><i class="fas fa-download"></i> <span id="${type}-${id}-count">${downloads.toLocaleString(currentLang==='pt-BR'?'pt-BR':'en-US')}</span></div>${extra||''}<a href="${downloadUrl||'#'}" class="download-btn" target="_blank" rel="noopener" data-type="${type}" data-id="${id}"><i class="fas fa-download"></i> ${btnTxt}</a></div>`; }
function loadBuilds(){ const c=document.getElementById('builds-container'); c.innerHTML=''; (config.builds||[]).forEach((b,i)=>{ const d=b.name[currentLang]||b.name['pt-BR']; const ds=b.description[currentLang]||b.description['pt-BR']; const card=document.createElement('div'); card.className='build-card'; card.style.animationDelay=`${i*0.1}s`; card.innerHTML=cardBase(d,ds,b.image,b.version,b.date,itemCount('build',b.id),translations[currentLang].download,'',b.download_url,'build',b.id); c.appendChild(card); }); bindDownloads(); }
function loadModules(){ const c=document.getElementById('modules-container'); c.innerHTML=''; (config.modulos||[]).forEach((m,i)=>{ const d=m.name[currentLang]||m.name['pt-BR']; const ds=m.description[currentLang]||m.description['pt-BR']; const tags=(m.tags?.[currentLang]||m.tags?.['pt-BR']||[]).map(t=>`<span class="module-tag">${t}</span>`).join(''); const extra=`<div class="module-tags">${tags}</div>`; const card=document.createElement('div'); card.className='module-card'; card.style.animationDelay=`${i*0.1}s`; card.innerHTML=`<img class="module-image" src="${m.image}" onerror="this.src='https://via.placeholder.com/400x200/12121a/a855f7?text=Module'"><div class="module-content"><h3>${d}</h3><p>${ds}</p>${extra}<div class="module-downloads"><i class="fas fa-download"></i> <span id="module-${m.id}-count">${itemCount('module',m.id).toLocaleString(currentLang==='pt-BR'?'pt-BR':'en-US')}</span></div><a href="${m.download_url||'#'}" class="download-btn" target="_blank" rel="noopener" data-type="module" data-id="${m.id}"><i class="fas fa-download"></i> ${translations[currentLang].download}</a></div>`; c.appendChild(card); }); bindDownloads(); }
function loadTeam(){ const c=document.getElementById('team-container'); c.innerHTML=''; (config.team||[]).forEach(m=>{ const n=m.name[currentLang]||m.name['pt-BR']; const r=m.role[currentLang]||m.role['pt-BR']; c.innerHTML += `<div class="team-member"><img src="${m.avatar}" class="team-avatar" onerror="this.src='https://via.placeholder.com/130x130/12121a/a855f7?text=Avatar'"><h3>${n}</h3><p class="team-role">${r}</p><div class="team-social"><a href="${m.social?.github||'#'}" target="_blank" rel="noopener"><i class="fab fa-github"></i></a></div></div>`; }); }
function loadDonation(){ const c=document.getElementById('donation-container'); c.innerHTML=''; (config.donation?.methods||[]).forEach(m=>{ const txt=m[currentLang]||m['pt-BR']; c.innerHTML += `<div class="donation-method"><h4><i class="fas fa-heart"></i> ${m.name}</h4><p>${m.url?`<a href="${m.url}" target="_blank" rel="noopener">${txt}</a>`:txt}</p></div>`; }); }
function loadSupport(){ const c=document.getElementById('support-container'); c.innerHTML=''; if(config.support?.discord) c.innerHTML += `<a class="support-link" href="${config.support.discord}" target="_blank" rel="noopener"><i class="fab fa-discord"></i><span>Discord</span></a>`; }
function bindDownloads(){ document.querySelectorAll('.download-btn').forEach(btn=>{ btn.onclick = async () => { await incrementDownload(btn.dataset.type, btn.dataset.id); }; }); }
function initializeSite(){ updateLanguage(); initCursorGlow(); initHeaderScroll(); bindDownloads(); }
document.getElementById('lang-toggle').addEventListener('click', ()=>{ currentLang = currentLang==='pt-BR'?'en':'pt-BR'; updateLanguage(); });
document.addEventListener('DOMContentLoaded', loadConfig);
