const translations={"pt-BR":{"site-title":"Minhas Builds","hero-title":"Todas as minhas builds de jogos e projetos","hero-subtitle":"Encontre aqui todas as versões disponíveis para download","builds-title":"Builds Disponíveis","modules-title":"Módulos","modules-description":"Módulos personalizados para expandir e melhorar suas builds","team-title":"Equipe","donation-title":"Apoie o Projeto","donation-description":"Se você gosta do meu trabalho, considere fazer uma doação para ajudar no desenvolvimento contínuo!","support-title":"Grupo de Suporte","support-description":"Junte-se ao nosso grupo de suporte para tirar dúvidas, compartilhar feedback e conversar com outros usuários","footer-text":"Feito com ❤️ por Vinicius Sad | 2026","download":"Baixar Agora","language":"English","total-downloads-text":"downloads totais"},"en":{"site-title":"My Builds","hero-title":"All my game builds and projects","hero-subtitle":"Find all available versions for download here","builds-title":"Available Builds","modules-title":"Modules","modules-description":"Custom modules to expand and improve your builds","team-title":"Team","donation-title":"Support the Project","donation-description":"If you like my work, consider donating to help with continuous development!","support-title":"Support Group","support-description":"Join our support group to ask questions, share feedback, and chat with other users","footer-text":"Made with ❤️ by Vinicius Sad | 2026","download":"Download Now","language":"Português","total-downloads-text":"total downloads"}};
let lang='pt-BR',config=window.siteConfig||{},data={totalDownloads:0,items:{}};
const set=(id,v)=>{const e=document.getElementById(id); if(e) e.textContent=v;};
const count=(type,id)=>Number(data.items?.[`${type}_${id}`]?.downloads||0);
async function loadData(){try{data=await GitHubDownloadAPI.readData()}catch{data={totalDownloads:0,items:{}}}}
function updateUI(){Object.entries(translations[lang]).forEach(([k,v])=>set(k,v)); document.documentElement.lang=lang; set('total-downloads-count',Number(data.totalDownloads||0).toLocaleString(lang==='pt-BR'?'pt-BR':'en-US'));}
function bind(){document.querySelectorAll('.download-btn').forEach(btn=>{btn.onclick=async(e)=>{e.preventDefault(); try{data=await GitHubDownloadAPI.updateItem(btn.dataset.type,btn.dataset.id); updateUI(); renderAll(); window.open(btn.getAttribute('href'),'_blank','noopener');}catch(err){console.error(err); window.open(btn.getAttribute('href'),'_blank','noopener');}}});}
function buildCard(type,id,title,desc,img,version,date,downloads,extra,downloadUrl){return `<img class="${type==='module'?'module-image':'build-image'}" src="${img}" onerror="this.src='https://via.placeholder.com/800x440/12121a/a855f7?text=Image'"><div class="${type==='module'?'module-content':'build-content'}"><h3>${title}</h3>${version?`<span class="build-version">v${version}</span>`:''}<p>${desc}</p>${date?`<p class="build-date"><i class="far fa-calendar"></i> ${date}</p>`:''}<div class="module-downloads"><i class="fas fa-download"></i> <span id="${type}_${id}_count">${downloads.toLocaleString(lang==='pt-BR'?'pt-BR':'en-US')}</span></div>${extra||''}<a class="download-btn" href="${downloadUrl}" target="_blank" rel="noopener" data-type="${type}" data-id="${id}"><i class="fas fa-download"></i> ${translations[lang].download}</a></div>`;}
function renderBuilds(){const c=document.getElementById('builds-container'); if(!c) return; c.innerHTML=''; (config.builds||[]).forEach(b=>{const n=b.name[lang]||b.name['pt-BR']; const d=b.description[lang]||b.description['pt-BR']; c.innerHTML+=`<div class="build-card">${buildCard('build',b.id,n,d,b.image,b.version,b.date,count('build',b.id),'',b.download_url)}</div>`});}
function renderModules(){const c=document.getElementById('modules-container'); if(!c) return; c.innerHTML=''; (config.modulos||[]).forEach(m=>{const n=m.name[lang]||m.name['pt-BR']; const d=m.description[lang]||m.description['pt-BR']; const tags=(m.tags?.[lang]||m.tags?.['pt-BR']||[]).map(x=>`<span class="module-tag">${x}</span>`).join(''); c.innerHTML+=`<div class="module-card">${buildCard('module',m.id,n,d,m.image,m.version,m.date,count('module',m.id),`<div class="module-tags">${tags}</div>`,m.download_url)}</div>`});}
function renderTeam(){const c=document.getElementById('team-container'); if(!c) return; c.innerHTML=''; (config.team||[]).forEach(m=>{const n=m.name[lang]||m.name['pt-BR']; const r=m.role[lang]||m.role['pt-BR']; c.innerHTML+=`<div class="team-member"><img class="team-avatar" src="${m.avatar}" onerror="this.src='https://via.placeholder.com/160x160/12121a/a855f7?text=Avatar'"><h3>${n}</h3><p class="team-role">${r}</p><div class="team-social"><a href="${m.social?.github||'#'}" target="_blank" rel="noopener"><i class="fab fa-github"></i></a></div></div>`});}
function renderDonation(){const c=document.getElementById('donation-container'); if(!c) return; c.innerHTML=''; (config.donation?.methods||[]).forEach(m=>{c.innerHTML+=`<div class="donation-method"><h4><i class="fas fa-heart"></i> ${m.name}</h4><p>${m[lang]||m['pt-BR']||''}</p></div>`});}
function renderSupport(){const c=document.getElementById('support-container'); if(!c) return; c.innerHTML=''; if(config.support?.discord) c.innerHTML+=`<a class="support-link" href="${config.support.discord}" target="_blank" rel="noopener"><i class="fab fa-discord"></i><span>Discord</span></a>`;}
function renderAll(){updateUI(); renderBuilds(); renderModules(); renderTeam(); renderDonation(); renderSupport(); bind();}
function initEffects(){const g=document.getElementById('cursorGlow'); if(g){document.addEventListener('mousemove',e=>{g.style.left=e.clientX+'px'; g.style.top=e.clientY+'px'; g.style.opacity='1';});} const h=document.getElementById('header'); if(h){window.addEventListener('scroll',()=>h.classList.toggle('scrolled',window.scrollY>100));}}
document.getElementById('lang-toggle').addEventListener('click',()=>{lang=lang==='pt-BR'?'en':'pt-BR'; renderAll();});
document.addEventListener('DOMContentLoaded',async()=>{try{await loadData(); renderAll(); initEffects();}catch(err){console.error(err); renderAll(); initEffects();}});